-- Create STUDENTS table
CREATE TABLE STUDENTS(
	ST_ID INT PRIMARY KEY,
	ST_NAME VARCHAR(20) NOT NULL,
	ST_LAST VARCHAR(20) NOT NULL
);

-- Insert sample data into the STUDENTS table
INSERT INTO STUDENTS(ST_ID, ST_NAME, ST_LAST) VALUES(1, 'Konul', 'Gurbanova');
INSERT INTO STUDENTS(ST_ID, ST_NAME, ST_LAST) VALUES(2, 'Shahnur', 'Isgandarli');
INSERT INTO STUDENTS(ST_ID, ST_NAME, ST_LAST) VALUES(3, 'Natavan', 'Mammadova');

SELECT * FROM STUDENTS;

-- Create INTERESTS TABLE
CREATE TABLE INTERESTS(
	STUDENT_ID INT NOT NULL,
	INTEREST VARCHAR(20) NOT NULL
);

-- Insert sample data into the INSERTS table
INSERT INTO INTERESTS(STUDENT_ID, INTEREST) VALUES(1, 'Tennis');
INSERT INTO INTERESTS(STUDENT_ID, INTEREST) VALUES(1, 'Literature');
INSERT INTO INTERESTS(STUDENT_ID, INTEREST) VALUES(2, 'Math');
INSERT INTO INTERESTS(STUDENT_ID, INTEREST) VALUES(2, 'Tennis');
INSERT INTO INTERESTS(STUDENT_ID, INTEREST) VALUES(3, 'Math');
INSERT INTO INTERESTS(STUDENT_ID, INTEREST) VALUES(3, 'Music');
INSERT INTO INTERESTS(STUDENT_ID, INTEREST) VALUES(2, 'Football');
INSERT INTO INTERESTS(STUDENT_ID, INTEREST) VALUES(1, 'Chemistry');
INSERT INTO INTERESTS(STUDENT_ID, INTEREST) VALUES(3, 'Chess');

SELECT * FROM INTERESTS;
