CREATE TABLE STUDENTS(
	ST_ID INT NOT NULL,
	ST_NAME VARCHAR(20) NOT NULL,
	ST_LAST VARCHAR(20) NOT NULL
);

SELECT * FROM STUDENTS;

INSERT INTO STUDENTS(ST_ID, ST_NAME, ST_LAST) VALUES(1, 'Konul', 'Gurbanova');
INSERT INTO STUDENTS(ST_ID, ST_NAME, ST_LAST) VALUES(2, 'Shahnur', 'Isgandarli');
INSERT INTO STUDENTS(ST_ID, ST_NAME, ST_LAST) VALUES(3, 'Natavan', 'Mammadova');

CREATE TABLE INTERESTS(
	STUDENT_ID INT NOT NULL,
	INTEREST VARCHAR(20) NOT NULL
);

SELECT * FROM INTERESTS;

INSERT INTO INTERESTS(STUDENT_ID, INTEREST) VALUES(1, 'Tennis');
INSERT INTO INTERESTS(STUDENT_ID, INTEREST) VALUES(1, 'Literature');
INSERT INTO INTERESTS(STUDENT_ID, INTEREST) VALUES(2, 'Math');
INSERT INTO INTERESTS(STUDENT_ID, INTEREST) VALUES(2, 'Tennis');
INSERT INTO INTERESTS(STUDENT_ID, INTEREST) VALUES(3, 'Math');
INSERT INTO INTERESTS(STUDENT_ID, INTEREST) VALUES(3, 'Music');
INSERT INTO INTERESTS(STUDENT_ID, INTEREST) VALUES(2, 'Football');
INSERT INTO INTERESTS(STUDENT_ID, INTEREST) VALUES(1, 'Chemistry');
INSERT INTO INTERESTS(STUDENT_ID, INTEREST) VALUES(3, 'Chess');


ALTER TABLE STUDENTS 
RENAME ST_ID TO STUDENT_ID;

SELECT * FROM STUDENTS;

ALTER TABLE STUDENTS
ALTER COLUMN ST_NAME TYPE VARCHAR(30);

ALTER TABLE STUDENTS
ALTER COLUMN ST_LAST TYPE VARCHAR(30);




