-- Rename the STUDENTS.ST_ID to STUDENTS.STUDENT_ID
ALTER TABLE STUDENTS
RENAME COLUMN ST_ID TO STUDENT_ID;

SELECT * FROM STUDENTS;

-- Change the length of STUDENTS.ST_NAME from 20 to 30
ALTER TABLE STUDENTS
ALTER COLUMN ST_NAME TYPE VARCHAR(30);


-- Change the length of STUDENTS.ST_LAST from 20 to 30
ALTER TABLE STUDENTS
ALTER COLUMN ST_LAST TYPE VARCHAR(30);

SELECT * FROM STUDENTS;

-- Change the name of the INTERESTS.INTEREST to INTERESTS
ALTER TABLE INTERESTS
RENAME COLUMN INTEREST TO INTERESTS;

SELECT * FROM INTERESTS;

-- Create new table with an array type that stores the INTERESTS table
CREATE TABLE TEMP_INTERESTS AS
SELECT STUDENT_ID,
       CONCAT('{', STRING_AGG(CONCAT('"', INTERESTS, '"'), ','), '}') AS INTERESTS
FROM INTERESTS
GROUP BY STUDENT_ID
ORDER BY STUDENT_ID;

SELECT * FROM TEMP_INTERESTS; 

-- Drop the old table
DROP TABLE INTERESTS;

-- Replace the TEMP_INTERESTS table with the INTERESTS table
ALTER TABLE TEMP_INTERESTS
RENAME TO INTERESTS;

SELECT * FROM INTERESTS;


