-- Rename back the STUDENTS.STUDENT_ID to STUDENTS.ST_ID
ALTER TABLE STUDENTS
RENAME COLUMN STUDENT_ID TO ST_ID;

SELECT * FROM STUDENTS;

-- Revert the change in the lenght of STUDENTS.ST_NAME from 30 to 20
ALTER TABLE STUDENTS
ALTER COLUMN ST_NAME TYPE VARCHAR(20);

-- Revert the change in the lenght of STUDENTS.ST_LAST from 30 to 20
ALTER TABLE STUDENTS
ALTER COLUMN ST_LAST TYPE VARCHAR(20);

SELECT * FROM STUDENTS;

-- Revert the name of the INTERESTS.INTERESTS to INTEREST
ALTER TABLE INTERESTS
RENAME COLUMN INTERESTS TO INTEREST;

SELECT * FROM INTERESTS;

-- Drop the previous version of INTERESTS table
DROP TABLE INTERESTS;

-- Recreate the dropped INTERESTS table
CREATE TABLE INTERESTS( 
	STUDENT_ID INT NOT NULL,
	INTEREST VARCHAR(20) NOT NULL
);

-- Re-insert the sample data into INTERESTS table
INSERT INTO INTERESTS(STUDENT_ID, INTEREST) VALUES(1, 'Tennis');
INSERT INTO INTERESTS(STUDENT_ID, INTEREST) VALUES(1, 'Literature');
INSERT INTO INTERESTS(STUDENT_ID, INTEREST) VALUES(2, 'Math');
INSERT INTO INTERESTS(STUDENT_ID, INTEREST) VALUES(2, 'Tennis');
INSERT INTO INTERESTS(STUDENT_ID, INTEREST) VALUES(3, 'Math');
INSERT INTO INTERESTS(STUDENT_ID, INTEREST) VALUES(3, 'Music');
INSERT INTO INTERESTS(STUDENT_ID, INTEREST) VALUES(2, 'Football');
INSERT INTO INTERESTS(STUDENT_ID, INTEREST) VALUES(1, 'Chemistry');
INSERT INTO INTERESTS(STUDENT_ID, INTEREST) VALUES(3, 'Chess');

SELECT * FROM INTERESTS;
       
